source 'https://rubygems.org'

gem 'ecrire',               '~> 0.6'
gem 'actionview',           '~> 4.1'
gem 'activemodel',          '~> 4.1'
gem 'actionmailer',         '~> 4.1'

gem 'warden',               '~> 1.2'
gem 'bcrypt',               '~> 3.1'
gem 'nokogiri',             '~> 1.6'
gem 's3',                   '~> 0.3'
gem 'pg',                   '~> 0.17'
gem 'kaminari',             '~> 0.15'

group :server do
  gem 'thin',               '~> 1.6'
end

group :assets do
  gem 'therubyracer'
  gem 'sass-rails',         '~> 4.0.3'
  gem 'sprockets-rails',    '~> 2.1'
  gem 'bourbon',            '~> 3.2'
  gem 'coffee-rails',       '~> 4.0'
  gem 'jquery-rails',       '~> 3.1'
  gem 'turbolinks',         '~> 2.2'
  gem 'uglifier',           '~> 2.5'
end
