source 'https://rubygems.org'

gem 'ecrire'

group :required do
  gem 'rails'
  gem 'observejs',         git: 'https://github.com/pothibo/observejs.git'
  gem 'written',           git: 'https://github.com/pothibo/written.git'
  gem 'warden'
  gem 'bcrypt'
  gem 'nokogiri'
  gem 's3'
  gem 'pg'
  gem 'pg_search'
  gem 'kaminari'

  gem 'sprockets-rails'
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'turbolinks'
  gem 'bourbon'
  gem 'uglifier'
  gem 'jbuilder'
end

gem 'byebug', group: :development
gem 'rails_12factor', group: :production

group :server do
  gem 'thin',             '~> 1.6'
end
