source 'https://rubygems.org'

gem 'ecrire',               git: 'https://github.com/pothibo/ecrire'

group :required do
  gem 'rails',             '~> 4.2'
  gem 'observejs',         git: 'https://github.com/pothibo/observejs'
  gem 'warden',            '~> 1.2'
  gem 'bcrypt',            '~> 3.1'
  gem 'nokogiri',          '~> 1.6'
  gem 's3',                '~> 0.3'
  gem 'pg',                '~> 0.17'
  gem 'kaminari',          '~> 0.15'

  gem 'sprockets-rails',   '~> 2.1'
  gem 'sass-rails',        '~> 4.0', '>= 4.0.3'
  gem 'coffee-rails',      '~> 4.0'
  gem 'turbolinks',        '~> 2.2'
  gem 'bourbon',           '~> 3.2'
  gem 'uglifier',          '~> 2.5'
  gem 'jbuilder',          '~> 2.2'
end

group :server do
  gem 'thin',             '~> 1.6'
end

# Only loaded in development environment.
group :development do
  gem 'byebug'
end
